version: "3.1"

services:
  mongo:
    image: mongo
    container_name: helloMongo
    restart: always
    environment:
      MONGO_INITDB_ROOM_USERNAME: root
      MONGO_INITDB_ROOM_PASSWORD: root
    ports:
      - 27019:27017
